base_url = "https://ihoronir.github.io"

title = "ihoronir.github.io"
description = "Ihoronir's website"

default_language = "ja"

compile_sass = true

minify_html = true

generate_feed = true

#taxonomies = [
#    {name = "entry-lists", feed = false},
#]


[markdown]
highlight_code = true
#highlight_theme = "kronuz"
highlight_theme = "visual-studio-dark"
external_links_target_blank = true

[slugify]
paths = "off"
taxonomies = "off"
anchors = "off"

[extra]
