base_url = "https://ihoronir.github.io"

compile_sass = true

minify_html = false

taxonomies = [
    {name = "entry_lists", feed = true},
]


[markdown]
highlight_code = true
highlight_theme = "kronuz"

[extra]
