on: push
name: Build and deploy on push
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - run: git
      - run: wget

  #jobs:
  #  build:
  #    name: shalzz/zola-deploy-action
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@master
  #    - name: shalzz/zola-deploy-action
  #      uses: shalzz/zola-deploy-action@master
  #      env:
  #        PAGES_BRANCH: gh-pages
  #        TOKEN: ${{ secrets.TOKEN }}
