on: push
name: Build and deploy on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - name: Setup Zola
      run: wget -q -O - "https://github.com/getzola/zola/releases/download/v0.14.1/zola-v0.14.1-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin

    - name: Build
      run: deno run --allow-net --allow-run ihoronigen.js build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

