on: push
name: Build and deploy on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: git
    - run: wget

      #jobs:
      #  hello:
      #    runs-on: ubuntu-latest
      #    steps:
      #      - uses: actions/checkout@master
      #      - uses: denolib/setup-deno@v1.1.0
      #        with:
      #          deno-version: 0.x
      #      - run: deno run https://deno.land/std/examples/welcome.ts

  #jobs:
  #  build:
  #    name: shalzz/zola-deploy-action
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@master
  #    - name: shalzz/zola-deploy-action
  #      uses: shalzz/zola-deploy-action@master
  #      env:
  #        PAGES_BRANCH: gh-pages
  #        TOKEN: ${{ secrets.TOKEN }}
