on: push
name: Build and deploy on push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - name: Install zola
      run: wget -q -O - "https://github.com/getzola/zola/releases/download/v0.14.1/zola-v0.14.1-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin

    - name: Build
      run: deno run --allow-net --allow-run build.ts

    - name: Deploy
      run: |
        cd public
        git config --global user.name "ihoronir"
        git config --global user.email "20489316+ihoronir@users.noreply.github.com"
        git init
        git remote set-url origin "https://github.com/ihoronir/ihoronir.github.io.git"
        git fetch
        git add .
        git commit -m "update"
        git push -f origin gh-pages


      #jobs:
      #  hello:
      #    runs-on: ubuntu-latest
      #    steps:
      #      - uses: actions/checkout@master
      #      - uses: denolib/setup-deno@v1.1.0
      #        with:
      #          deno-version: 0.x
      #      - run: deno run https://deno.land/std/examples/welcome.ts

  #jobs:
  #  build:
  #    name: shalzz/zola-deploy-action
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@master
  #    - name: shalzz/zola-deploy-action
  #      uses: shalzz/zola-deploy-action@master
  #      env:
  #        PAGES_BRANCH: gh-pages
  #        TOKEN: ${{ secrets.TOKEN }}
